src/TPSymfony/BibliBundle/Entity/Links.php
<?php

namespace TPSymfony\BibliBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Links
 *
 * @ORM\Table(name="links")
 * @ORM\Entity(repositoryClass="TPSymfony\BibliBundle\Repository\LinksRepository")
 */
class Links
{
	/**
	 * @ORM\ManyToOne(targetEntity="TPSymfony\BibliBundle\Entity\Article")
	 *  * @ORM\JoinColumn(name="idArticle", referencedColumnName="idArticle")
	 */
	private $article;
	
	/**
	 * @var int
	 *
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="link", type="string", length=255, nullable=true)
	 */
	private $link;
	
	
	
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="author", type="string", length=255, nullable=true))
	 */
	private $author;
	
	/**
	 * @var \DateTime
	 *
	 * @ORM\Column(name="date", type="datetime", nullable=true))
	 */
	private $date;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="description", type="string", length=255, nullable=true))
	 */
	private $description;
	
	
	/**
	 * Get id
	 *
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}
	
	/**
	 * Set link
	 *
	 * @param string $link
	 *
	 * @return Links
	 */
	public function setLink($link)
	{
		$this->link = $link;
		
		return $this;
	}
	
	/**
	 * Get link
	 *
	 * @return string
	 */
	public function getLink()
	{
		return $this->link;
	}
	
	/**
	 * Set author
	 *
	 * @param string $author
	 *
	 * @return Links
	 */
	public function setAuthor($author)
	{
		$this->author = $author;
		
		return $this;
	}
	
	/**
	 * Get author
	 *
	 * @return string
	 */
	public function getAuthor()
	{
		return $this->author;
	}
	
	/**
	 * Set date
	 *
	 * @param \DateTime $date
	 *
	 * @return Links
	 */
	public function setDate($date)
	{
		$this->date = $date;
		
		return $this;
	}
	
	/**
	 * Get date
	 *
	 * @return \DateTime
	 */
	public function getDate()
	{
		return $this->date;
	}
	
	/**
	 * Set description
	 *
	 * @param string $description
	 *
	 * @return Links
	 */
	public function setDescription($description)
	{
		$this->description = $description;
		
		return $this;
	}
	
	/**
	 * Get description
	 *
	 * @return string
	 */
	public function getDescription()
	{
		return $this->description;
	}
	/**
	 * @return mixed
	 */
	public function getArticle(){
		return $this->article;
	}
	
	/**
	 * @param mixed $article
	 */
	public function setArticle($article){
		$this->article = $article;
	}

    /**
     * @return int
     */
    public function getReferencement(){
        return 10;
    }
	
}

src/TPSymfony/BibliBundle/Resources/views/Default/ajouterArticle.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ include ('TPSymfonyBibliBundle:Default:menuConnecte.html.twig') }}
{% endblock %}

{% block body %}

    <h2>Ajouter un article</h2>

    <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 gauche">


        {{ form_start(ajoutArticleForm) }}

        <div class="form-group">

            <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.title) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.title) }}
                    {{ form_widget(ajoutArticleForm.title, {'attr': {'class': 'form-control'}}) }}
                </div>

              </div></br>
            
             <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.subtitle) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.subtitle) }}
                    {{ form_widget(ajoutArticleForm.subtitle, {'attr': {'class': 'form-control'}}) }}
                </div>

            </div></br>
            
             <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.isbn) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.isbn) }}
                    {{ form_widget(ajoutArticleForm.isbn, {'attr': {'class': 'form-control'}}) }}
                </div>

            </div></br>
            
           <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.type) }}
                </div>
                <div class="col-md-8 input90 checker">
                    {{ form_errors(ajoutArticleForm.type) }}
                    {{ form_widget(ajoutArticleForm.type) }}
                </div>

            </div></br>
           
             <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.editor) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.editor) }}
                    {{ form_widget(ajoutArticleForm.editor, {'attr': {'class': 'form-control'}}) }}
                </div>

            </div></br>

            <div class="row">
                <div class="col-md-4">

                    {{ form_label(ajoutArticleForm.date) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.date) }}
                    {{ form_widget(ajoutArticleForm.date, {'attr': {'class': 'form-control'}}) }}
                    <!-- IL FAUT LAISSER LA CLASS FORM-CONTROL sinon la date n'est pas visible sur Windows-->
                </div>

            </div></br>

            <div class="row">
                <div class="col-md-4">

                    {{ form_label(ajoutArticleForm.tags) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.tags) }}
                    {{ form_widget(ajoutArticleForm.tags, {'attr': {'class': 'form-control'}}) }}
                </div>

             </div></br>

            <div class="row">
                <div class="col-md-4">

                    {{ form_label(ajoutArticleForm.brochure) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.brochure) }}
                    {{ form_widget(ajoutArticleForm.brochure) }}
                </div>

            </div></br>
            
            
            <h2>Renseigner les elements connexes a l'article</h2>
            
             <div class="row">
                <div class="col-md-4">

                    {{ form_label(ajoutArticleForm.dataset) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.dataset) }}
                    {{ form_widget(ajoutArticleForm.dataset) }}
                </div>

            </div></br>
            
            <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.comments) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.comments) }}
                    {{ form_widget(ajoutArticleForm.comments, {'attr': {'class': 'form-control'}}) }}
                </div>
      </div></br>
      
            <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.hypothesis) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_errors(ajoutArticleForm.hypothesis) }}
                    {{ form_widget(ajoutArticleForm.hypothesis, {'attr': {'class': 'form-control'}}) }}
                </div>

                 </div></br>
            
            <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.conclusions) }}
                    {{ form_errors(ajoutArticleForm.conclusions) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_widget(ajoutArticleForm.conclusions, {'attr': {'class': 'form-control'}}) }}
                </div>

                </div></br>
                
                 <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.experiments) }}
                    {{ form_errors(ajoutArticleForm.experiments) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_widget(ajoutArticleForm.experiments, {'attr': {'class': 'form-control'}}) }}
                </div>

                </div></br>
                
                 <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.links) }}
                    {{ form_errors(ajoutArticleForm.links) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_widget(ajoutArticleForm.links, {'attr': {'class': 'form-control'}}) }}
                </div>

                </div></br>
                 <div class="row">
                <div class="col-md-4">
                    {{ form_label(ajoutArticleForm.contributors) }}
                    {{ form_errors(ajoutArticleForm.contributors) }}
                </div>
                <div class="col-md-8 input90">
                    {{ form_widget(ajoutArticleForm.contributors, {'attr': {'class': 'form-control'}}) }}
                </div>

                </div></br>
                
                
                
        </div>

        {{ form_widget(ajoutArticleForm.ajouterArticle, {'attr': {'class': 'btn btn-danger'}}) }}
        {{ form_widget(ajoutArticleForm.annuler, {'attr': {'class': 'btn btn-info'}}) }}

        {{ form_end(ajoutArticleForm) }}
    </div>


{% endblock %}

src/TPSymfony/BibliBundle/Resources/views/Default/ajouterOk.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ include ('TPSymfonyBibliBundle:Default:menuConnecte.html.twig') }}
{% endblock %}

{% block body %}

    <div class="row" >

    <h3>L'article a été ajouté avec succès</h3>
        <div class ="row"></div>

    <a href="{{ path('ajouterArticle')}}"><input type="button" class="btn btn-primary" value="Ajouter un autre article"/></a>
    <a href="{{ path('listeArticleAuteur')}}"><input type="button" class="btn btn-info" value="Revenir à la liste des articles"/></a>

    </div>


{% endblock %}

src/TPSymfony/BibliBundle/Resources/views/Default/detailArticle.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ include ('TPSymfonyBibliBundle:Default:menuConnecte.html.twig') }}
{% endblock %}

{% block body %}
    <table class="table table-bordered">
        <h2>Détails de l'article</h2>

        <tbody>


        <tr>
            <td><strong>ISBN </strong></td>
            <td>{{ article.isbn }}</td>
        </tr>

        <tr>
            <td><strong>Title </strong></td>
            <td>{{ article.title }}</td>
        </tr>
                <tr>
            <td><strong>Type </strong></td>
            <td>{{ article.type }}</td>
        </tr>

        <tr>
            <td><strong>Contributors </strong></td>
            <td>
                {% for unContri in contributors if contributors !=null %}
                    {{ unContri.name }} ,
                {% endfor %}
            </td>
        </tr>

        <tr>
            <td><strong>Date </strong></td>
            <td> {{ article.getDate()|date('d-m-Y') }}</td>
        </tr>

        <tr>
            <td><strong>Tags </strong></td>
            <td>{{ article.tags }}</td>
        </tr>

        <tr>
            <td><strong>Editor </strong></td>
            <td>{{ article.editor }}</td>
        </tr>

        <tr>
            <td><strong>PDF </strong></td>
            <td> <a href="{{ path('afficherBrochure', {'pdfFilename':article.brochure}) }}">{{ article.brochure }}</a></td>
        </tr>
        <tr>
            <td><strong>Dataset</strong></td>
            <td> <a href="{{ path('afficherDataset', {'pdfFilename':article.dataset}) }}">{{ article.dataset }}</a></td>
        </tr>

        <tr>
            <td><strong>Hypothesis </strong></td>
            <td>{{ article.hypothesis }}</td>
        </tr>

        <tr>
            <td><strong>Conclusion </strong></td>
            <td>{{ article.conclusions }}</td>
        </tr>
        
        <tr>
            <td><strong>Experiments </strong></td>
            <td>{{ article.experiments }}</td>
        </tr>
        
        <tr>
            <td><strong>Links </strong></td>
            <td>{{ article.links }}</td>
        </tr>
        
        <tr>
            <td><strong>Partners </strong></td>
            <td>{{ article.contributors }}</td>
        </tr>

        </tbody>
    </table>



{% endblock %}

src/TPSymfony/BibliBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dauphine Research Operation System{% endblock %}


{% block header %}

        {% if is_granted('ROLE_USER') %}
        {{ include ('TPSymfonyBibliBundle:Default:menuConnecte.html.twig') }}
        {% else %}
            {{ include ('TPSymfonyBibliBundle:Default:menuNonConnecte.html.twig') }}
     {% endif %}

{% endblock %}

{% block body %}

    <section id = "presentation">
        <h2>Présentation générale</h2>
        <p>Bienvenue au nouveau centre de gestion des articles <br /> de Dauphine. <br />
            <br />
            Vous pouvez vous <a href="login">connecter</a> ou <a href="register">créer un compte</a> <br/>
            afin de profiter toutes fonctionnalités du site Internet.
        </p>
    </section
{% endblock %}

src/TPSymfony/BibliBundle/Resources/views/Default/menuConnecte.html.twig
{% block header %}
    <nav class="navbar navbar-inverse">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-11">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">Dauphine Research Operation System</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-10">
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="/">Accueil</a></li>
                            <li><a href="{{ path('listeArticleAuteur')}}">Mes articles</a></li>
                            <li><a href="{{ path('listeArticle')}}">Tous les articles</a></li>
                            <li><a href="{{ path('ajouterArticle')}}">Ajouter un article</a></li>
                            <li><a href="{{ path('statistiques')}}">Statistiques</a></li>
                            <li><a href="/logout"><span class="glyphicon glyphicon-user"></span>Déconnexion</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </nav>

{% endblock %}

src/TPSymfony/BibliBundle/Resources/views/Default/menuNonConnecte.html.twig
<nav class="navbar navbar-inverse">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Dauphine Research Operating System</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="/">Accueil</a></li>
                    <li><a href="/listeDesArticles">Liste des articles</a></li>
                    <li><a href="/login"><span class="glyphicon glyphicon-user"></span>Se connecter</a></li>
                    <li><a href="/register"><span class="glyphicon glyphicon-log-in"></span>Créer un compte</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</nav>

src/TPSymfony/BibliBundle/Resources/views/Default/mesArticles.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ include ('TPSymfonyBibliBundle:Default:menuConnecte.html.twig') }}
{% endblock %}

{% block body %}
    <table class="table table-bordered">
        <h2>Mes articles publiés</h2>
        <thead>
        <tr>
            <td><strong>Identifiant</strong></td>
            <td><strong>Title</strong></td>
            <td><strong>Date</strong></td>
            <td><strong>Tags</strong></td>
            <td><strong>Référencement</strong></td>
            <td><strong>PDF</strong></td>
        </tr>
        </thead>

        <tbody>
        {% for unArticle in article %}
            <tr>

                <td> {{ unArticle.idArticle }}</td>
                <td> <a href="{{ path('afficherDetail', {'idArticle':unArticle.idArticle}) }}">{{ unArticle.title }}</a></td>
                <td> {{ unArticle.getDate()|date('d-m-Y') }}</td>
                <td> {{ unArticle.tags }}</td>
                <td> {{ unArticle.referencement }}%</td>
                  <td>  {% if unArticle.getBrochure() %} <a href="{{ path('afficherBrochure', {'pdfFilename':unArticle.brochure}) }}"> PDF</a> {% endif %}</td>

                <td><a href="{{ path('modifierArticle', {'idArticle':unArticle.idArticle, 'title':unArticle.title})}}"><input type="button" class="btn btn-primary" value="Modifier"/></a></td>
                <td><a href="{{ path('supprimerArticle', {'idArticle':unArticle.idArticle, 'title':unArticle.title})}}"><input type="button" class="btn btn-warning" value="Supprimer"/></a></td>

            </tr>
        {% endfor %}
        </tbody>
    </table>


    {% if is_granted('ROLE_ADMIN') %}
        <td><a href="{{ path('ajouterArticle')}}"><input type="button" class="btn btn-success" value="Ajouter un article"/></a></td>
    {% endif %}


{% endblock %}

src/TPSymfony/BibliBundle/Resources/views/Default/modifierArticle.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ include ('TPSymfonyBibliBundle:Default:menuConnecte.html.twig') }}
{% endblock %}

    {% block body %}
        <h2>Modifier un article</h2>

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 gauche">

                        {{ form_start(modifArticleForm) }}
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4">
                                    {{ form_label(modifArticleForm.title) }}
                                </div>
                                <div class="col-md-8 input90">
                                    {{ form_errors(modifArticleForm.title) }}
                                    {{ form_widget(modifArticleForm.title, {'attr': {'class': 'form-control'}}) }}
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    {{ form_label(modifArticleForm.date) }}
                                </div>
                                <div class="col-md-8 input90">
                                    {{ form_errors(modifArticleForm.date) }}
                                    {{ form_widget(modifArticleForm.date) }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    {{ form_label(modifArticleForm.tags) }}
                                </div>
                                <div class="col-md-8 input90">
                                    {{ form_errors(modifArticleForm.tags) }}
                                    {{ form_widget(modifArticleForm.tags, {'attr': {'class': 'form-control'}}) }}
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-4">
                                    {{ form_label(modifArticleForm.brochure) }}
                                </div>
                                <div class="col-md-8 input90">
                                    {{ form_errors(modifArticleForm.brochure) }}
                                    {{ form_widget(modifArticleForm.brochure, {'attr': {'class': 'form-control','disabled' :'disabled'}}) }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    {{ form_label(modifArticleForm.newBrochure) }}
                                </div>
                                <div class="col-md-8 input90">
                                    {{ form_errors(modifArticleForm.newBrochure) }}
                                    {{ form_widget(modifArticleForm.newBrochure) }}
                                </div>
                            </div>

                        </div>
                        
                        <div class="row">
                                <div class="col-md-4">
                                    {{ form_label(modifArticleForm.dataset) }}
                                </div>
                                <div class="col-md-8 input90">
                                    {{ form_errors(modifArticleForm.dataset) }}
                                    {{ form_widget(modifArticleForm.dataset, {'attr': {'class': 'form-control','disabled' :'disabled'}}) }}
                                </div>
                            </div>

                           

                    
                    
                            <h2>Modifier les elements connexes a l'article</h2>
            
                  <div class="row">
                                <div class="col-md-4">
                                    {{ form_label(modifArticleForm.newDataset) }}
                                </div>
                                <div class="col-md-8 input90">
                                    {{ form_errors(modifArticleForm.newDataset) }}
                                    {{ form_widget(modifArticleForm.newDataset) }}
                                </div>
                            </div>
            
                        <div class="row">
                            <div class="col-md-4">
                                {{ form_label(modifArticleForm.comments) }}
                            </div>
                            <div class="col-md-8 input90">
                                {{ form_errors(modifArticleForm.comments) }}
                                {{ form_widget(modifArticleForm.comments, {'attr': {'class': 'form-control'}}) }}
                            </div>
            
                        </div>
                        
                        <div class="row">
                            <div class="col-md-4">
                                {{ form_label(modifArticleForm.hypothesis) }}
                            </div>
                            <div class="col-md-8 input90">
                                {{ form_errors(modifArticleForm.hypothesis) }}
                                {{ form_widget(modifArticleForm.hypothesis, {'attr': {'class': 'form-control'}}) }}
                            </div>
            
                        </div>
                        
                        <div class="row">
                            <div class="col-md-4">
                                {{ form_label(modifArticleForm.conclusions) }}
                                {{ form_errors(modifArticleForm.conclusions) }}
                            </div>
                            <div class="col-md-8 input90">
                                {{ form_widget(modifArticleForm.conclusions, {'attr': {'class': 'form-control'}}) }}
                            </div>
            
                        </div>
                        
                         <div class="row">
                            <div class="col-md-4">
                                {{ form_label(modifArticleForm.experiments) }}
                                {{ form_errors(modifArticleForm.experiments) }}
                            </div>
                            <div class="col-md-8 input90">
                                {{ form_widget(modifArticleForm.experiments, {'attr': {'class': 'form-control'}}) }}
                            </div>
            
                        </div>
                        
                         <div class="row">
                            <div class="col-md-4">
                                {{ form_label(modifArticleForm.links) }}
                                {{ form_errors(modifArticleForm.links) }}
                            </div>
                            <div class="col-md-8 input90">
                                {{ form_widget(modifArticleForm.links, {'attr': {'class': 'form-control'}}) }}
                            </div>
            
                        </div>
                        
                         <div class="row">
                            <div class="col-md-4">
                                {{ form_label(modifArticleForm.contributors) }}
                                {{ form_errors(modifArticleForm.contributors) }}
                            </div>
                            <div class="col-md-8 input90">
                                {{ form_widget(modifArticleForm.contributors, {'attr': {'class': 'form-control'}}) }}
                            </div>
            
                        </div>

                    {{ form_widget(modifArticleForm.modifierArticle, {'attr': {'class': 'btn btn-danger'}}) }}
                    {{ form_widget(modifArticleForm.annuler, {'attr': {'class': 'btn btn-info'}}) }}

                    {{ form_end(modifArticleForm) }}


            </div>
            <div class="col-md-2"></div>
        </div>

    {% endblock %}

src/TPSymfony/BibliBundle/Resources/views/Default/tousArticles.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ include ('TPSymfonyBibliBundle:Default:menuConnecte.html.twig') }}
{% endblock %}

{% block body %}

    <div class="row">
        <h2>Tous les articles publiés</h2>
        <div class="col-md-2"></div>
        <div class="col-md-8 gauche">

            <table class="table table-bordered">
                <h4>Rechercher un article</h4>
                <tbody>
                {{ form_start(rechercheArticleForm) }}
                <tr>
                    <td>
                        <div class="col-md-4">
                            {{ form_label(rechercheArticleForm.title) }}
                        </div>
                        <div class="col-md-8 input90">
                            {{ form_errors(rechercheArticleForm.title) }}
                            {{ form_widget(rechercheArticleForm.title, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </td>
                    <td>
                        {{ form_widget(rechercheArticleForm.rechercherArticleByTitle, {'attr': {'class': 'btn btn-danger'}}) }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col-md-4">
                            {{ form_label(rechercheArticleForm.tags) }}
                        </div>
                        <div class="col-md-8 input90">
                            {{ form_errors(rechercheArticleForm.tags) }}
                            {{ form_widget(rechercheArticleForm.tags, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </td>
                    <td>
                        {{  form_widget(rechercheArticleForm.rechercherArticleByTags, {'attr': {'class': 'btn btn-danger'}}) }}
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col-md-4">
                            {{ form_label(rechercheArticleForm.date) }}
                        </div>
                        <div class="col-md-10 input90">
                            {{ form_errors(rechercheArticleForm.date) }}
                            {{ form_widget(rechercheArticleForm.date, {'attr': {'class': 'form-control'}}) }}
                            <!-- IL FAUT LAISSER LA CLASS FORM-CONTROL sinon la date n'est pas visible sur Windows-->
                        </div>
                    </td>
                    <td>
                        {{  form_widget(rechercheArticleForm.rechercherArticleByDate, {'attr': {'class': 'btn btn-danger'}}) }}
                    </td>
                </tr>
                {{ form_end(rechercheArticleForm) }}
                </tbody>
            </table>

        </div>
        <div class="col-md-2"></div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <td><strong>Identifiant</strong></td>
                <td><strong>Title</strong></td>
                 <td><strong>Type</strong></td>
                <td><strong>Date</strong></td>
                <td><strong>Tags</strong></td>
                <td><strong>PDF</strong></td>
                <td><strong>Référencement</strong></td>
            </tr>
            </thead>

            <tbody>
            {% for unArticle in article %}
                <tr>
                    <td> {{ unArticle.idArticle }}</td>
                    <td> <a href="{{ path('afficherDetail', {'idArticle':unArticle.idArticle}) }}">{{ unArticle.title }}</a></td>
                    <td> {{ unArticle.type }}</td>
                    <td> {{ unArticle.getDate()|date('d-m-Y') }}</td>
                    <td> {{ unArticle.tags }}</td>
                    <td>  {% if unArticle.getBrochure() %} <a href="{{ path('afficherBrochure', {'pdfFilename':unArticle.brochure}) }}"> PDF</a> {% endif %}</td>
                    <td> {{ unArticle.referencement}}%</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <td><a href="{{ path('ajouterArticle')}}"><input type="button" class="btn btn-success" value="Ajouter un article"/></a></td>




    </div>


{% endblock %}